USE MASTER;

IF NOT EXISTS (
  SELECT
    name
  FROM
    sys.databases
  WHERE
    name = N'QLThuePhong'
) CREATE DATABASE QLThuePhong;

USE QLThuePhong;

-- Tao table
CREATE TABLE PHONG (
  MaPhong CHAR(10) PRIMARY KEY,
  SoGiuong INT NOT NULL,
  NVPhuTrach NVARCHAR(50) NOT NULL,
  GiaTien DECIMAL(8, 2) NOT NULL,
  GhiChu NVARCHAR(MAX)
);

CREATE TABLE KHACHHANG(
  MaKH INT IDENTITY(1, 1) PRIMARY KEY,
  TenKH NVARCHAR(50) NOT NULL,
  DiaChi NVARCHAR(100) NOT NULL,
  SDT NVARCHAR(12) NOT NULL,
  GhiChu NVARCHAR(MAX)
);

CREATE TABLE THUEPHONG(
  MaKH INT,
  MaPhong CHAR(10),
  NgayLayPhong DATE,
  NgayTraPhong DATE NOT NULL,
  TienDaTra DECIMAL(8, 2) NOT NULL,
  GhiChu NVARCHAR(MAX),
  PRIMARY KEY (MaKH, MaPhong, NgayLayPhong),
  CONSTRAINT FK_MaKH FOREIGN KEY (MaKH) REFERENCES KHACHHANG(MaKH),
  CONSTRAINT FK_MaPhong FOREIGN KEY (MaPhong) REFERENCES PHONG(MaPhong),
);

-- Them records
-- Them PHONG
SELECT
  *
FROM
  PHONG;

INSERT INTO
  PHONG (MaPhong, SoGiuong, NVPhuTrach, GiaTien)
VALUES
  ('PHONG00001', 1, 'Nguyen Van A', 100.0);

INSERT INTO
  PHONG (MaPhong, SoGiuong, NVPhuTrach, GiaTien)
VALUES
  ('PHONG00002', 2, 'Tran Thi B', 200);

INSERT INTO
  PHONG (MaPhong, SoGiuong, NVPhuTrach, GiaTien)
VALUES
  ('PHONG00003', 1, 'Tran Thi B', 150);